# Persistence layer: Mongo
db:
  image: pemarchandet/mongo-congres-avef-snvel:v1.1.0
  extends:
    file: common.yml
    service: db
  restart: always
# Application server: NodeJS (Meteor)
appserver:
  image: pemarchandet/appserver-congres-avef-snvel:v2.0.0
  extends:
    file: common.yml
    service: appserver
  links:
    - db
  environment:
    ROOT_URL: "https://congres-avef-snvel.fr"
  restart: always
# Admin server: NodeJS (Meteor)
adminserver:
  image: pemarchandet/adminserver-congres-avef-snvel:v2.0.0
  extends:
    file: common.yml
    service: adminserver
  links:
    - db
  environment:
    ROOT_URL: "https://congres-avef-snvel.fr/admin"
  restart: always
# Front layer, static file, SSL, proxy cache: NGinx
front:
  image: pemarchandet/nginx-congres-avef-snvel:v2.0.0
  extends:
    file: common.yml
    service: front
  links:
    - appserver
    - adminserver
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "prod"
  restart: always
