# Persistence layer: Mongo
db:
  image: pemarchandet/mongo-congres-avef-snvel:v1.0.0
  extends:
    file: common.yml
    service: db
  restart: always
# Application server: NodeJS (Meteor)
server:
  image: pemarchandet/meteor-congres-avef-snvel:v1.0.0
  extends:
    file: common.yml
    service: server
  links:
    - db
  environment:
    ROOT_URL: "https://congres-avef-snvel.fr"
  restart: always
# Front layer, static file, SSL, proxy cache: NGinx
front:
  image: pemarchandet/nginx-congres-avef-snvel:v1.0.0
  extends:
    file: common.yml
    service: front
  links:
    - server
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "prod"
  restart: always
