# Persistence layer: Mongo
db:
  extends:
    file: common.yml
    service: db
# Application server: NodeJS (Meteor)
appserver:
  extends:
    file: common.yml
    service: appserver
  links:
    - db
  environment:
    ROOT_URL: "https://192.168.1.50"
# Admin server: NodeJS (Meteor)
adminserver:
  extends:
    file: common.yml
    service: adminserver
  links:
    - db
  environment:
    ROOT_URL: "https://192.168.1.50/admin"
# Front layer, static file, SSL, proxy cache: NGinx
front:
  extends:
    file: common.yml
    service: front
  links:
    - appserver
    - adminserver
  environment:
    # Can be: dev, pre, prod
    HOST_TARGET: "dev"
